#!/bin/bash
# Copyright (C) 2018 Amith Kini

# Shows the brightness using the light tool
# https://github.com/haikarainen/light
# Install by using make; (sudo) make install;


echo $(light)%


case $BLOCK_BUTTON in
	4) $(light -A 5);;
	5) $(light -U 5);;
	*) ;;
esac

