#!/bin/bash

# Take a screenshot
scrot /tmp/bg.png

# Pixellate it 10x
#mogrify -scale 10% -scale 1000% /tmp/screen_locked.png
convert /tmp/bg.png -filter Gaussian -blur 0x5 /tmp/bg.png

# Lock screen displaying this image.
i3lock -i /tmp/bg.png

# Turn the screen off after a delay.
sleep 60; pgrep i3lock && xset dpms force off
